show_error("Server should not be receiving commands sent by itself", true)

